const mockBios = [
    "I don't care about whales inside a spaghet",
    "There must be at least 57 snakes in this valley!",
    "Awwww! A snake will eat that laptop",
    "ducks are very small and like mammoths",
    "hippos are very helpful and don't care about gharials",
    "Awwww! The duck will pat that laptop",
    "Aren't seals just so big?",
    "THE TROUT! It's eating the sneaky girl!",
    "dogs are very helpful and love horses",
    "THE BEAR! It's eating the big laptop!",
    "There must be at least 6 beavers in here!",
    "Awwww! The toad will befriend that onion",
    "Aren't hippos just so unusual?",
    "There must be at least 57 whales over there!",
    "This monkey is so helpful!",
    "When you're on Wikipedia for three hours and then realize you know everything about the history of Macedonia",
    "I love cows inside a keyboard",
    "I love rhinos inside an onion",
    "In Soviet Russia, the Pokemon catch you!",
    "Oh, elephants are SO CUTE!",
    "Awwww! A turkey will pat that keyboard",
    "that valley is the best place to help frogs",
    "Awwww! That crayfish will kill that girl",
    "This duck is so unusual!",
    "this valley is the best place to kick jellyfish",
    "When you're on Wikipedia for three hours and then realize you know everything about spiders",
    "the island is the best place to ride herrings",
    "that island is the best place to grin at alligators",
    "For sure, worms are the best animals, because they eat laptops so well!",
    "Awwww! A cod will ride that laptop",
    "that valley is the best place to eat rats",
    "I hate toads inside a house",
    "For sure, donkeys are the best animals, because they kick spaghets so well!"
];
// credit to https://perchance.org/utnx6ioo1m
export default mockBios;